name: Deploy to Server

on:
  push:
    branches:
      - main  # Triggera il workflow solo su push al branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usa un runner Ubuntu per eseguire il job

    steps:
    # Passaggio 1: Check out il codice dal repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Passaggio 2: Impostazione della chiave SSH per la connessione al server
    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SERVER_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Sostituisci $SERVER_HOST con l'hostname o l'IP del server
        HOST="192.168.188.87"  # Modifica questa riga con il tuo server
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        
        # Assicurati che la chiave SSH sia caricata
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        
        # Test della connessione SSH
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 $SERVER_USER@$HOST "echo 'SSH connection successful'"

    # Passaggio 3: Esegui il pull dal repository sul server
    - name: Pull latest changes on the server
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o ConnectTimeout=10 $SERVER_USER@$HOST "
          cd /path/to/your/repository &&
          git pull origin main &&
          echo 'Pull completed successfully'
        "

    # Passaggio 4: Esegui qualsiasi altro comando necessario sul server
    - name: Restart server service (optional)
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o ConnectTimeout=10 $SERVER_USER@$HOST "sudo systemctl restart your-service-name"
